CREATE TABLE HOSPITAL_MGMT.DOCTOR(DOCTOR_NAME VARCHAR(100),
PATIENT_ID NUMERIC,
DOCTOR_SPECIAL VARCHAR(255),
DOCTOR_ID INT,
WARD_NAME VARCHAR(100),
PRIMARY KEY (DOCTOR_ID),
FOREIGN KEY (PATIENT_ID)
REFERENCES HOSPITAL_MGMT.PATIENT(PATIENT_ID));
