CREATE TABLE HOSPITAL_MGMT.WARDS(
    WARD_NAME VARCAHR(100) NOT NULL,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL,
    BED_CAPACITY INT,
    AVAILABLE_BEDS INT,
    CONSULTANT_ID INT,
    NURSE_CAPACITY INT,
    PRIMARY KEY (WARD_NAME)
);

CREATE TABLE HOSPITAL_MGMT.MEDICATIONS(
    MED_ID INT NOT NULL,
    MED_NAME VARCHAR(100) NOT NULL, 
    MED_AVAILABLE BOOLEAN,
    MED_AMOUNT INT,
    MED_EXPIRY DATE,
    MED_PRICE DECIMAL
);

CREATE TABLE HOSPITAL_MGMT.PRICE(
    PROCEDURE_ID INT NOT NULL,
    PROCDEURE_NAME VARCHAR(50) NOT NULL,
    PROCEDURE_PRICE DECIMAL
);