CREATE TABLE HOSPITAL_MGMT.NURSE(
    NURSE_NAME VARCHAR(100),
    NURSE_ID INT, -- ID will be an INT
    NURSE_LEVEL NUMERIC,
    IS_STUDENT_TRAINEE_INVOLVED BOOLEAN,
    WARD_NAME VARCHAR(100),
    NURSE_SPECIALITY VARCHAR(100),
    PATIENT_ID NUMERIC,
    PRIMARY KEY (NURSE_ID),
    FOREIGN KEY (PATIENT_ID)
    REFERENCES HOSPITAL_MGMT.PATIENT(PATIENT_ID)
    );
