CREATE DATABASE HOSPITAL_MGMT;

USE HOSPITAL_MGMT;

CREATE TABLE INPATIENT(
	patient_name VARCHAR(50) NOT NULL,
	patient_id INT NOT NULL PRIMARY KEY,
	gender VARCHAR(20) NOT NULL,
	address VARCHAR(50) NOT NULL,
	bed_no VARCHAR(20) NOT NULL,
	admission_date DATE NOT NULL,
	discharge_date DATE,
	lab_no INT, -- add foreign key
	doctor_id INT, -- add foreign key
	disease VARCHAR(50) NOT NULL
);

CREATE TABLE ROOM (
	bed_no VARCHAR(20) NOT NULL PRIMARY KEY,
	room_type VARCHAR(20) NOT NULL,
	ward_name VARCHAR(20) NOT NULL,
    ward_type VARCHAR(20) NOT NULL, 
	patient_id INT, 
	FOREIGN KEY (patient_id) REFERENCES INPATIENT(patient_id)
);

CREATE TABLE APPOINTMENTS (
	appointment_id INT NOT NULL PRIMARY KEY,
    appointment_type VARCHAR(50) NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    appointment_duration VARCHAR(50),
    doctor_id INT NOT NULL -- add foreign key 
);

CREATE TABLE BILL(
BILL_NO INT NOT NULL,
PATIENT_ID INT, 
PATIENT_TYPE VARCHAR(10),
DOCTOR_CHARGE INT NOT NULL,
MEDICINE_CHARGE INT NOT NULL,
ROOM_CHARGE INT NOT NULL,
OPERATION_CHARGE INT,
NUMBER_OF_DAYS INT,
NURSING_CHARGE INT,
ADVANCE INT,
HEALTH_CARD VARCHAR(50),
LAB_CHARGE INT,
BILL INT,
PRIMARY KEY (BILL_NO),
FOREIGN KEY (PATIENT_ID) REFERENCES INPATIENT(PATIENT_ID)
);

CREATE TABLE ADMINISTRATOR(
A_ID INT,
A_NAME VARCHAR(20) NOT NULL,
GENDER VARCHAR(10) NOT NULL,
PRIMARY KEY (A_ID)
);

-- added appoinment id to this table - you can use the appointment id to find the patients which will have outpatients appointments
CREATE TABLE OUTPATIENTS(
PATIENT_ID INT, 
appointment_id INT NOT NULL,
LAB_NO INT, -- add foreign key
PRIMARY KEY (PATIENT_ID),
FOREIGN KEY (appointment_id) REFERENCES APPOINTMENTS(appointment_id)
);

DROP TABLE if exists DOCTOR;
CREATE TABLE DOCTOR(DOCTOR_NAME VARCHAR(100),
DOCTOR_SPECIAL VARCHAR(255),
DOCTOR_ID INT,
WARD_NAME VARCHAR(100),
PRIMARY KEY (DOCTOR_ID)
);

DROP TABLE if exists NURSE;
CREATE TABLE NURSE(NURSE_NAME VARCHAR(100),
NURSE_ID INT,
NURSE_LEVEL NUMERIC,
IS_STUDENT_TRAINEE_INVOLVED BOOLEAN,
WARD_NAME VARCHAR(100),
NURSE_SPECIALITY VARCHAR(100),
PRIMARY KEY (NURSE_ID)
);

DROP TABLE if exists LAB;
CREATE TABLE LAB
(LAB_NO INT(50) NOT NULL,
PATIENT_ID INT NOT NULL,
WEIGHT INT NOT NULL,
DOCTOR_ID INT,
LAB_DATE DATETIME NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
PATIENT_TYPE VARCHAR(50) NOT NULL,
AMOUNT INT(100) NOT NULL,
PRIMARY KEY (LAB_NO),
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTOR(DOCTOR_ID));

ALTER TABLE APPOINTMENTS ADD foreign key(doctor_id) references DOCTOR(DOCTOR_ID);
ALTER TABLE inpatient ADD foreign key(doctor_id) references DOCTOR(DOCTOR_ID);
ALTER TABLE INPATIENT ADD FOREIGN KEY(LAB_NO) REFERENCES LAB(LAB_NO);
ALTER TABLE OUTPATIENTS ADD FOREIGN KEY(LAB_NO) REFERENCES LAB(LAB_NO);
ALTER TABLE LAB ADD FOREIGN KEY (PATIENT_ID) REFERENCES OUTPATIENT(PATIENT_ID);


